Translate responses.md (v9.x)
laravel-taiwan/docs pull request #467
Opened 2022-06-18 08:24 UTC by hope51607

2022-08-21 02:28 UTC, flamerecca requested changes

2022-08-21 02:28 UTC, flamerecca commented on responses.md
>      - [Redirecting To External Domains](#redirecting-external-domains)
這行沒有翻譯到

2022-08-21 02:28 UTC, flamerecca commented on responses.md
>  You may attach a cookie to an outgoing `Illuminate\Http\Response` instance using the `cookie` method. You should pass the name, value, and the number of minutes the cookie should be considered valid
這行沒有翻譯到

2022-08-21 02:28 UTC, flamerecca commented on responses.md
>  #### Streamed Downloads
這行沒有翻譯到

2022-08-21 02:29 UTC, flamerecca requested changes

2022-08-21 02:29 UTC, flamerecca commented on responses.md
>      - [Redirecting To External Domains](#redirecting-external-domains)
這行沒有翻譯到

2022-08-21 05:17 UTC, hope51607 commented on responses.md
>      - [Redirecting To External Domains](#redirecting-external-domains)
我這兩個禮拜剛好比較忙 
之後會補上

2022-09-11 13:01 UTC, flamerecca commented
時間有點久了，先合併，之後盤點時進行調整

2022-09-11 13:01 UTC, merged