Translate seeding.md (v9.x)
laravel-taiwan/docs pull request #474
Opened 2022-07-11 09:30 UTC by IMingGarson

翻譯資料填充文件到繁體中文

2022-07-11 09:31 UTC, IMingGarson commented
@Nationalcat 再請您給我一些回饋。

2022-07-27 08:07 UTC, Nationalcat requested changes
class 會有單複數問題，應翻譯成 `類別`

2022-07-27 08:07 UTC, Nationalcat commented on seeding.md
> +> {技巧} 您可以給 `run` 方法任何您需要的依賴作為參數型態，Laravel 會透過 [服務容器](/docs/{{version}}/container) 自動使用這些參數型態。
{tip} 是有作用的，請不要翻譯

2022-07-27 08:07 UTC, Nationalcat commented on seeding.md
> +在 `run` 方法內，您可以用任何方式新增您的資料，如使用 [query builder](/docs/{{version}}/queries) 來手動輸入資料或使用 [Eloquent model factories](/docs/{{version}}/database-testing#defining-model-factories) 來建立資料。
`[]` 裡面的文字也需要翻譯

2022-07-27 08:07 UTC, Nationalcat commented on seeding.md
> +您可以透過執行 `db:seed` Artisan command 來建立資料到資料庫內。預設情況下，`db:seed` 會執行 `Database\Seeders\DatabaseSeeder` 這個 Class，而該 Class 可以用於呼叫其他 Seeder Classes。然而，您可以使用 `--class` 參數來指定您想執行的 Seeder Class。
`Artisan command` => `Artisan 指令`,
`Class `, `Classes` => `類別`

2022-07-27 08:07 UTC, Nationalcat commented on seeding.md
> +若您想刪掉現有的資料表並重新建立資料，您也可以使用 `migrate:fresh` 與 `--seed`，這種做法對於重新建立資料庫是十分方便的。
該指令可用於重建整個資料庫。

2022-07-27 08:07 UTC, Nationalcat commented on seeding.md
> +  - [撰寫Seeders](#撰寫seeders)
中文與英文未間隔

2022-07-27 08:07 UTC, Nationalcat commented on seeding.md
> +- [資料庫：資料填充](#資料庫seeding)
這邊的 `#` 都不要翻譯，這是用來連結內文 `<a name=""></a>` 的錨點

2022-07-28 04:05 UTC, IMingGarson commented on seeding.md
> +> {技巧} 您可以給 `run` 方法任何您需要的依賴作為參數型態，Laravel 會透過 [服務容器](/docs/{{version}}/container) 自動使用這些參數型態。
Class/Classes 均改為「類別」
tip不翻譯，改回原樣

2022-07-28 04:06 UTC, IMingGarson commented on seeding.md
> +在 `run` 方法內，您可以用任何方式新增您的資料，如使用 [query builder](/docs/{{version}}/queries) 來手動輸入資料或使用 [Eloquent model factories](/docs/{{version}}/database-testing#defining-model-factories) 來建立資料。
query builder 修正為 查詢產生器
Eloquent model factories 修正為 模型工廠

2022-07-28 04:06 UTC, IMingGarson commented on seeding.md
> +若您想刪掉現有的資料表並重新建立資料，您也可以使用 `migrate:fresh` 與 `--seed`，這種做法對於重新建立資料庫是十分方便的。
整句已修正為「該指令可用於重建整個資料庫。」

2022-07-28 04:06 UTC, IMingGarson commented on seeding.md
> +  - [撰寫Seeders](#撰寫seeders)
間隔已補上

2022-07-28 04:07 UTC, IMingGarson commented on seeding.md
> +- [資料庫：資料填充](#資料庫seeding)
錨點已修復，並按照原md排版

2022-07-28 04:07 UTC, IMingGarson commented on seeding.md
> +您可以透過執行 `db:seed` Artisan command 來建立資料到資料庫內。預設情況下，`db:seed` 會執行 `Database\Seeders\DatabaseSeeder` 這個 Class，而該 Class 可以用於呼叫其他 Seeder Classes。然而，您可以使用 `--class` 參數來指定您想執行的 Seeder Class。
已根據上述回饋修正

2022-07-28 04:08 UTC, Nationalcat requested changes

2022-07-28 04:08 UTC, Nationalcat commented on seeding.md
> +    類別DatabaseSeeder extends Seeder
這行是程式碼，不能翻譯喔

2022-07-28 04:08 UTC, Nationalcat commented on seeding.md
> +            PostSeeder::類別,
不能翻譯程式碼且非註解的部分

2022-07-28 04:08 UTC, Nationalcat commented on seeding.md
> +該指令可用於重建整個資料庫。
若您想刪掉現有的資料表並重新建立資料，您也可以使用 `migrate:fresh` 與 `--seed`，該指令可用於重建整個資料庫。

2022-07-28 04:08 UTC, Nationalcat commented on seeding.md
> +                UserSeeder::類別,
保留原文

2022-07-28 04:08 UTC, Nationalcat commented on seeding.md
> +    類別DatabaseSeeder extends Seeder
保留原文

2022-07-28 04:13 UTC, IMingGarson commented on seeding.md
> +該指令可用於重建整個資料庫。
Sorry我誤會了，已補上，請重整看最新的內容

2022-07-28 04:14 UTC, IMingGarson commented on seeding.md
> +    類別DatabaseSeeder extends Seeder
是，我一開始用全部替代，一時沒注意到（汗
剛剛已經修正，下方有些也是不小心被我替代到的

2022-10-01 03:36 UTC, flamerecca commented
討論時間偏久，這邊先合併，之後再行修正

2022-10-01 03:36 UTC, merged