Update installation.md
laravel-taiwan/docs pull request #479
Opened 2022-09-07 15:34 UTC by XimenZangief

2022-09-08 05:01 UTC, flamerecca requested changes
以下再麻煩翻譯

2022-09-09 13:42 UTC, XimenZangief reviewed
installation.md 翻譯完成

2022-09-09 14:04 UTC, flamerecca commented on installation.md
> +> {tip} 如果你想要在開發你的 Laravel 應用程式時搶個，考慮看看我們的入門套件。 Laravel 入門套件會為你的 Laravel 應用程式提供前後端驗證的基本結構。
這邊有點更動，新的文件有包含
```
> **Note** 
```

再麻煩調整，感謝

2022-09-09 14:10 UTC, XimenZangief commented on installation.md
> +> {tip} 如果你想要在開發你的 Laravel 應用程式時搶個，考慮看看我們的入門套件。 Laravel 入門套件會為你的 Laravel 應用程式提供前後端驗證的基本結構。
已修正

2022-09-11 12:39 UTC, flamerecca approved these changes

2022-09-11 12:39 UTC, merged